services:
  - type: web
    name: tgm-backend
    env: python
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 main:app
    envVars:
      - key: FLASK_APP
        value: main.py
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGIN
        fromService:
          name: tgm-frontend
          type: web
          property: url
    autoDeploy: true

  - type: web
    name: tgm-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: tgm-backend
          type: web
          property: url
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache